# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:41
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160116_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=accounts.models.PhoneField(max_length=20),
        ),
    ]
